language: python
python:
  - "2.7"
before_install:
  - apt-get update
  - git clone --recursive https://github.com/ipython/ipython.git
install:
  - apt-get install libzmq3-dev
  - cd ipython && pip install -e ".[notebook]" && cd ..
  - pip install -r requirements.txt
script:
  - nosetests nbgrader
